language: bash
deploy:
  -
    provider: script
    script: .travis/deploy_prod.sh
    on:
      repo: SvenDub/RankingGame
      branch: master
  -
    provider: script
    script: .travis/deploy_dev.sh
    on:
      repo: SvenDub/RankingGame
      branch: develop
